export const RESOURCE_ID__SHARED__AGE = "RESOURCE_ID__SHARED__AGE";
export const RESOURCE_ID__VISA__STUDY = "RESOURCE_ID__VISA__STUDY";
export const RESOURCE_ID__VISA__COOP = "RESOURCE_ID__VISA__COOP";
export const RESOURCE_ID__VISA__WORKING_HOLIDAY =
  "RESOURCE_ID__VISA__WORKING_HOLIDAY";
export const RESOURCE_ID__STATUS__WORKER = "RESOURCE_ID__STATUS__WORKER";
export const RESOURCE_ID__STATUS__STUDENT = "RESOURCE_ID__STATUS__STUDENT";
